apiVersion: v1
kind: Service
metadata:
  name: web-app-lb
  namespace: microservices
spec:
  type: LoadBalancer
  selector:
    app: nginx-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
